# Generated by Django 4.1.1 on 2022-11-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_partner_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partner',
            new_name='Message',
        ),
    ]
